/* Canonical synchronized grade content: 71 records shared with the Android source. */
var PAIZOMATH_GRADE_QUESTIONS = [] = [
  { id: "a-m-1", grade: "A Δημοτικού", category: "math", difficulty: "beginner", prompt: "Η Άννα έχει 5 μολύβια και παίρνει άλλα 3. Πόσα έχει τώρα;", choices: ["7", "8", "9", "10"], answerIndex: 1, explanation: "Προσθέτουμε 5 και 3: 5 + 3 = 8." },
  { id: "a-m-2", grade: "A Δημοτικού", category: "math", difficulty: "beginner", prompt: "Ποιος αριθμός έρχεται μετά το 19;", choices: ["18", "20", "21", "29"], answerIndex: 1, explanation: "Μετά το 19 έρχεται το 20." },
  { id: "a-l-1", grade: "A Δημοτικού", category: "language", difficulty: "beginner", prompt: "Με ποιο γράμμα αρχίζει η λέξη «μήλο»;", choices: ["Μ", "Λ", "Π", "Τ"], answerIndex: 0, explanation: "Η λέξη «μήλο» αρχίζει από το γράμμα Μ." },
  { id: "a-l-2", grade: "A Δημοτικού", category: "language", difficulty: "beginner", prompt: "Ποια λέξη είναι το όνομα ενός παιδιού;", choices: ["τρέχω", "Μαρία", "κόκκινο", "γρήγορα"], answerIndex: 1, explanation: "Η Μαρία είναι κύριο όνομα." },
  { id: "a-s-1", grade: "A Δημοτικού", category: "science", difficulty: "beginner", prompt: "Με ποιο μέρος του σώματος μυρίζουμε;", choices: ["Με τη μύτη", "Με το χέρι", "Με το πόδι", "Με το αυτί"], answerIndex: 0, explanation: "Η μύτη είναι το όργανο της όσφρησης." },
  { id: "a-k-1", grade: "A Δημοτικού", category: "knowledge", difficulty: "beginner", prompt: "Πόσοι μήνες έχει ένας χρόνος;", choices: ["7", "10", "12", "15"], answerIndex: 2, explanation: "Ένας χρόνος έχει δώδεκα μήνες." },
  { id: "a-en-1", grade: "A Δημοτικού", category: "english", difficulty: "beginner", prompt: "Τι σημαίνει η λέξη “sun”;", choices: ["Ήλιος", "Φεγγάρι", "Αστέρι", "Θάλασσα"], answerIndex: 0, explanation: "Η αγγλική λέξη “sun” σημαίνει ήλιος." },
  { id: "a-sk-1", grade: "A Δημοτικού", category: "skills", difficulty: "beginner", prompt: "Ποιο βήμα βοηθά πριν ξεκινήσεις μια εργασία;", choices: ["Να ετοιμάσω τα υλικά μου", "Να πετάξω τα βιβλία", "Να φωνάξω", "Να μην ακούσω"], answerIndex: 0, explanation: "Η προετοιμασία των υλικών βοηθά να ξεκινήσουμε οργανωμένα." },

  { id: "b-m-1", grade: "B Δημοτικού", category: "math", difficulty: "beginner", prompt: "Πόσο κάνει 23 + 14;", choices: ["35", "36", "37", "38"], answerIndex: 2, explanation: "23 + 14 = 37." },
  { id: "b-m-2", grade: "B Δημοτικού", category: "math", difficulty: "beginner", prompt: "Πόσο κάνει 50 − 20;", choices: ["20", "30", "40", "70"], answerIndex: 1, explanation: "Αν αφαιρέσουμε 2 δεκάδες από 5 δεκάδες, μένουν 3 δεκάδες: 30." },
  { id: "b-l-1", grade: "B Δημοτικού", category: "language", difficulty: "beginner", prompt: "Ποια είναι η σωστή πληθυντική μορφή του «δέντρο»;", choices: ["δέντρες", "δέντρα", "δεντρά", "δέντρι"], answerIndex: 1, explanation: "Ο πληθυντικός της λέξης «δέντρο» είναι «δέντρα»." },
  { id: "b-l-2", grade: "B Δημοτικού", category: "language", difficulty: "beginner", prompt: "Ποια λέξη είναι ρήμα;", choices: ["σχολείο", "πράσινος", "χορεύω", "τσάντα"], answerIndex: 2, explanation: "Το «χορεύω» δείχνει μια πράξη, άρα είναι ρήμα." },
  { id: "b-s-1", grade: "B Δημοτικού", category: "science", difficulty: "beginner", prompt: "Ποιο από αυτά είναι υγρό;", choices: ["Γάλα", "Πέτρα", "Μολύβι", "Αέρας"], answerIndex: 0, explanation: "Το γάλα ρέει και παίρνει το σχήμα του δοχείου, άρα είναι υγρό." },
  { id: "b-k-1", grade: "B Δημοτικού", category: "knowledge", difficulty: "beginner", prompt: "Ποια ημέρα έρχεται μετά την Κυριακή;", choices: ["Σάββατο", "Δευτέρα", "Τρίτη", "Παρασκευή"], answerIndex: 1, explanation: "Μετά την Κυριακή αρχίζει η νέα εβδομάδα με τη Δευτέρα." },
  { id: "b-p-1", grade: "B Δημοτικού", category: "physical", difficulty: "beginner", prompt: "Τι κάνουμε όταν διψάμε μετά την άσκηση;", choices: ["Πίνουμε νερό", "Δεν αναπνέουμε", "Τρέχουμε χωρίς στάση", "Φοράμε βαρύ παλτό"], answerIndex: 0, explanation: "Το νερό βοηθά το σώμα να ενυδατωθεί." },
  { id: "b-a-1", grade: "B Δημοτικού", category: "arts", difficulty: "beginner", prompt: "Ποια γραμμή είναι καμπύλη;", choices: ["Μια γραμμή σαν τόξο", "Μια ευθεία γραμμή", "Ένας αριθμός", "Ένα γράμμα"], answerIndex: 0, explanation: "Η καμπύλη γραμμή αλλάζει κατεύθυνση και μοιάζει με τόξο." },

  { id: "c-m-1", grade: "Γ Δημοτικού", category: "math", difficulty: "explorer", prompt: "Πόσο κάνει 7 × 8;", choices: ["48", "54", "56", "64"], answerIndex: 2, explanation: "Επτά φορές το οκτώ κάνει 56." },
  { id: "c-m-2", grade: "Γ Δημοτικού", category: "math", difficulty: "explorer", prompt: "Πόσο κάνει 72 ÷ 8;", choices: ["7", "8", "9", "10"], answerIndex: 2, explanation: "Επειδή 8 × 9 = 72, τότε 72 ÷ 8 = 9." },
  { id: "c-m-3", grade: "Γ Δημοτικού", category: "math", difficulty: "explorer", prompt: "Ένα μάθημα αρχίζει στις 09:00 και τελειώνει στις 10:00. Πόση ώρα διαρκεί;", choices: ["30 λεπτά", "1 ώρα", "2 ώρες", "3 ώρες"], answerIndex: 1, explanation: "Από τις 09:00 έως τις 10:00 περνά μία ώρα." },
  { id: "c-l-1", grade: "Γ Δημοτικού", category: "language", difficulty: "explorer", prompt: "Ποια πρόταση γράφεται σωστά;", choices: ["η Μαρία παίζει.", "Η Μαρία παίζει.", "Η μαρία Παίζει.", "η μαρία παίζει."], answerIndex: 1, explanation: "Η πρόταση αρχίζει με κεφαλαίο γράμμα και τελειώνει με τελεία." },
  { id: "c-g-1", grade: "Γ Δημοτικού", category: "geography", difficulty: "explorer", prompt: "Ποια κατεύθυνση δείχνει συνήθως το πάνω μέρος ενός χάρτη;", choices: ["Βορρά", "Νότο", "Ανατολή", "Δύση"], answerIndex: 0, explanation: "Στους περισσότερους χάρτες ο Βορράς βρίσκεται προς τα πάνω." },
  { id: "c-s-1", grade: "Γ Δημοτικού", category: "science", difficulty: "explorer", prompt: "Ποια αλλαγή συμβαίνει όταν το νερό ζεσταίνεται πολύ;", choices: ["Γίνεται υδρατμός", "Γίνεται πέτρα", "Γίνεται χώμα", "Γίνεται μέταλλο"], answerIndex: 0, explanation: "Με τη θέρμανση το νερό μπορεί να εξατμιστεί και να γίνει υδρατμός." },
  { id: "c-h-1", grade: "Γ Δημοτικού", category: "history", difficulty: "explorer", prompt: "Τι μπορεί να μας δείξει ένα παλιό νόμισμα;", choices: ["Στοιχεία για το παρελθόν", "Τον αυριανό καιρό", "Μόνο το βάρος του", "Μια συνταγή"], answerIndex: 0, explanation: "Τα αντικείμενα του παρελθόντος είναι πηγές που βοηθούν τους ιστορικούς." },
  { id: "c-t-1", grade: "Γ Δημοτικού", category: "technology", difficulty: "explorer", prompt: "Τι κάνουμε πριν πατήσουμε έναν άγνωστο σύνδεσμο;", choices: ["Ελέγχουμε με έναν έμπιστο ενήλικα", "Δίνουμε τον κωδικό μας", "Τον στέλνουμε παντού", "Πατάμε βιαστικά"], answerIndex: 0, explanation: "Η προσεκτική χρήση συνδέσμων βοηθά να μένουμε ασφαλείς στο διαδίκτυο." },

  { id: "d-m-1", grade: "Δ Δημοτικού", category: "math", difficulty: "explorer", prompt: "Πόσο είναι το 1/4 του 20;", choices: ["4", "5", "10", "15"], answerIndex: 1, explanation: "Χωρίζουμε το 20 σε 4 ίσα μέρη: 20 ÷ 4 = 5." },
  { id: "d-m-2", grade: "Δ Δημοτικού", category: "math", difficulty: "explorer", prompt: "Πόσο κάνει 346 + 127;", choices: ["463", "473", "483", "493"], answerIndex: 1, explanation: "346 + 127 = 473." },
  { id: "d-m-3", grade: "Δ Δημοτικού", category: "math", difficulty: "explorer", prompt: "Πόσα εκατοστά είναι 2 μέτρα;", choices: ["20", "100", "200", "2.000"], answerIndex: 2, explanation: "Κάθε μέτρο έχει 100 εκατοστά, άρα 2 μέτρα έχουν 200 εκατοστά." },
  { id: "d-l-1", grade: "Δ Δημοτικού", category: "language", difficulty: "explorer", prompt: "Ποιο είναι το επίθετο στην πρόταση «Το γρήγορο τρένο έφυγε»;", choices: ["Το", "γρήγορο", "τρένο", "έφυγε"], answerIndex: 1, explanation: "Το «γρήγορο» περιγράφει το ουσιαστικό «τρένο», άρα είναι επίθετο." },
  { id: "d-l-2", grade: "Δ Δημοτικού", category: "language", difficulty: "explorer", prompt: "Ποιο σημείο στίξης ταιριάζει στο τέλος της πρότασης «Πρόσεξε»;", choices: ["Τελεία", "Ερωτηματικό", "Θαυμαστικό", "Κόμμα"], answerIndex: 2, explanation: "Το θαυμαστικό ταιριάζει σε μια δυνατή προτροπή ή εντολή." },
  { id: "d-s-1", grade: "Δ Δημοτικού", category: "science", difficulty: "explorer", prompt: "Σε μια τροφική αλυσίδα, ποιο ζώο τρώει συνήθως τα φυτά;", choices: ["Το φυτοφάγο", "Το θηρευτικό", "Το μικρόβιο", "Το μέταλλο"], answerIndex: 0, explanation: "Τα φυτοφάγα ζώα τρέφονται με φυτά." },
  { id: "d-g-1", grade: "Δ Δημοτικού", category: "geography", difficulty: "explorer", prompt: "Τι είναι ένα νησί;", choices: ["Στεριά που περιβάλλεται από νερό", "Πολύ ψηλό βουνό", "Ένας ποταμός", "Μια έρημος"], answerIndex: 0, explanation: "Το νησί είναι κομμάτι στεριάς με νερό γύρω του." },
  { id: "d-c-1", grade: "Δ Δημοτικού", category: "civics", difficulty: "explorer", prompt: "Τι βοηθά να λυθεί μια διαφωνία στην ομάδα;", choices: ["Ήρεμη συζήτηση", "Φωνές", "Κοροϊδία", "Να μη μιλά κανείς"], answerIndex: 0, explanation: "Η ήρεμη συζήτηση βοηθά να ακουστούν όλες οι απόψεις και να βρεθεί λύση." },

  { id: "e-m-1", grade: "Ε Δημοτικού", category: "math", difficulty: "champion", prompt: "Πόσο κάνει 3,5 + 1,2;", choices: ["4,5", "4,6", "4,7", "5,7"], answerIndex: 2, explanation: "3,5 + 1,2 = 4,7." },
  { id: "e-m-2", grade: "Ε Δημοτικού", category: "math", difficulty: "champion", prompt: "Ποιο κλάσμα είναι ίσο με 2/4;", choices: ["1/2", "1/3", "2/3", "3/4"], answerIndex: 0, explanation: "Αν διαιρέσουμε αριθμητή και παρονομαστή του 2/4 με 2, παίρνουμε 1/2." },
  { id: "e-m-3", grade: "Ε Δημοτικού", category: "math", difficulty: "champion", prompt: "Ποιο είναι το εμβαδόν ορθογωνίου με μήκος 8 εκ. και πλάτος 3 εκ.;", choices: ["11 τ.εκ.", "16 τ.εκ.", "22 τ.εκ.", "24 τ.εκ."], answerIndex: 3, explanation: "Εμβαδόν = μήκος × πλάτος, άρα 8 × 3 = 24 τ.εκ." },
  { id: "e-l-1", grade: "Ε Δημοτικού", category: "language", difficulty: "champion", prompt: "Ποια λέξη είναι σύνδεσμος;", choices: ["και", "βιβλίο", "τρέχω", "γρήγορος"], answerIndex: 0, explanation: "Ο σύνδεσμος «και» ενώνει λέξεις ή προτάσεις." },
  { id: "e-h-1", grade: "Ε Δημοτικού", category: "history", difficulty: "champion", prompt: "Ποια πόλη ήταν πρωτεύουσα της Βυζαντινής Αυτοκρατορίας;", choices: ["Κωνσταντινούπολη", "Σπάρτη", "Ρώμη", "Αλεξάνδρεια"], answerIndex: 0, explanation: "Η Κωνσταντινούπολη ήταν η πρωτεύουσα της Βυζαντινής Αυτοκρατορίας." },
  { id: "e-g-1", grade: "Ε Δημοτικού", category: "geography", difficulty: "champion", prompt: "Τι δείχνει η κλίμακα ενός χάρτη;", choices: ["Τη σχέση της απόστασης στον χάρτη με την πραγματική απόσταση", "Τη θερμοκρασία", "Τις ώρες της ημέρας", "Το ύψος των ανθρώπων"], answerIndex: 0, explanation: "Η κλίμακα μάς βοηθά να υπολογίζουμε πραγματικές αποστάσεις από έναν χάρτη." },
  { id: "e-s-1", grade: "Ε Δημοτικού", category: "science", difficulty: "champion", prompt: "Ποια μορφή ενέργειας χρησιμοποιεί ένα ηλιακό πάνελ;", choices: ["Ηλιακή ενέργεια", "Μόνο ηχητική ενέργεια", "Μόνο χημική ενέργεια", "Μόνο μυϊκή ενέργεια"], answerIndex: 0, explanation: "Το ηλιακό πάνελ αξιοποιεί το φως του Ήλιου για να παράγει ηλεκτρική ενέργεια." },
  { id: "e-en-1", grade: "Ε Δημοτικού", category: "english", difficulty: "champion", prompt: "Ποια πρόταση σημαίνει «Μου αρέσει η επιστήμη»;", choices: ["I like science.", "I am science.", "Science likes I.", "Like is science."], answerIndex: 0, explanation: "Η φράση “I like science.” σημαίνει «Μου αρέσει η επιστήμη»." },

  { id: "f-m-1", grade: "ΣΤ Δημοτικού", category: "math", difficulty: "champion", prompt: "Πόσο είναι το 25% του 80;", choices: ["10", "20", "25", "40"], answerIndex: 1, explanation: "Το 25% είναι το ένα τέταρτο. Το ένα τέταρτο του 80 είναι 20." },
  { id: "f-m-2", grade: "ΣΤ Δημοτικού", category: "math", difficulty: "champion", prompt: "Πόσο κάνει 4,8 ÷ 0,6;", choices: ["0,8", "6", "8", "80"], answerIndex: 2, explanation: "4,8 ÷ 0,6 = 8, επειδή 0,6 × 8 = 4,8." },
  { id: "f-m-3", grade: "ΣΤ Δημοτικού", category: "math", difficulty: "champion", prompt: "Μια συνταγή για 4 άτομα χρειάζεται 300 γρ. αλεύρι. Πόσα χρειάζεται για 8 άτομα;", choices: ["150 γρ.", "300 γρ.", "450 γρ.", "600 γρ."], answerIndex: 3, explanation: "Τα άτομα διπλασιάζονται, οπότε διπλασιάζουμε και το αλεύρι: 300 × 2 = 600 γρ." },
  { id: "f-l-1", grade: "ΣΤ Δημοτικού", category: "language", difficulty: "champion", prompt: "Ποια πρόταση είναι σε ενεργητική φωνή;", choices: ["Το γράμμα γράφτηκε από τη Μαρία.", "Η Μαρία έγραψε το γράμμα.", "Το γράμμα θα γραφτεί.", "Το γράμμα έχει γραφτεί."], answerIndex: 1, explanation: "Στην ενεργητική φωνή το υποκείμενο, η Μαρία, κάνει την ενέργεια." },
  { id: "f-h-1", grade: "ΣΤ Δημοτικού", category: "history", difficulty: "champion", prompt: "Τι είναι ένα Σύνταγμα;", choices: ["Ο βασικός νόμος ενός κράτους", "Μια αρχαία πόλη", "Ένα μουσικό όργανο", "Ένα είδος χάρτη"], answerIndex: 0, explanation: "Το Σύνταγμα περιγράφει βασικούς κανόνες οργάνωσης ενός κράτους και τα δικαιώματα των πολιτών." },
  { id: "f-s-1", grade: "ΣΤ Δημοτικού", category: "science", difficulty: "champion", prompt: "Ποιο σύστημα του σώματος παίρνει οξυγόνο από τον αέρα;", choices: ["Αναπνευστικό", "Πεπτικό", "Μυϊκό", "Σκελετικό"], answerIndex: 0, explanation: "Το αναπνευστικό σύστημα μάς βοηθά να παίρνουμε οξυγόνο." },
  { id: "f-t-1", grade: "ΣΤ Δημοτικού", category: "technology", difficulty: "champion", prompt: "Ποιος κωδικός είναι πιο ασφαλής;", choices: ["123456", "password", "Μόνο το όνομά μου", "Μια μεγάλη φράση με γράμματα, αριθμούς και σύμβολα"], answerIndex: 3, explanation: "Οι μεγάλες, μοναδικές φράσεις με διαφορετικούς χαρακτήρες είναι δυσκολότερο να μαντευτούν." },
  { id: "f-c-1", grade: "ΣΤ Δημοτικού", category: "civics", difficulty: "champion", prompt: "Τι σημαίνει να συμμετέχουμε δημοκρατικά σε μια απόφαση τάξης;", choices: ["Ακούμε απόψεις και ψηφίζουμε με σεβασμό", "Αποφασίζει πάντα ένας", "Φωνάζουμε πιο δυνατά", "Δεν ακούμε κανέναν"], answerIndex: 0, explanation: "Η δημοκρατική συμμετοχή βασίζεται στον διάλογο, τον σεβασμό και τη δίκαιη διαδικασία." },

  { id: "g1-m-1", grade: "Α Γυμνασίου", category: "math", difficulty: "genius", prompt: "Λύσε την εξίσωση: x + 7 = 19.", choices: ["x = 10", "x = 12", "x = 19", "x = 26"], answerIndex: 1, explanation: "Αφαιρούμε 7 και από τις δύο πλευρές: x = 19 − 7 = 12." },
  { id: "g1-m-2", grade: "Α Γυμνασίου", category: "math", difficulty: "genius", prompt: "Πόσο κάνει −4 + 9;", choices: ["−13", "−5", "5", "13"], answerIndex: 2, explanation: "Ξεκινώντας από το −4 και προχωρώντας 9 μονάδες προς τα δεξιά, φτάνουμε στο 5." },
  { id: "g1-m-3", grade: "Α Γυμνασίου", category: "math", difficulty: "genius", prompt: "Αν 3 τετράδια κοστίζουν 6 €, πόσο κοστίζουν 5 τετράδια στην ίδια τιμή;", choices: ["8 €", "9 €", "10 €", "12 €"], answerIndex: 2, explanation: "Κάθε τετράδιο κοστίζει 6 ÷ 3 = 2 €. Άρα 5 τετράδια κοστίζουν 10 €." },
  { id: "g1-s-1", grade: "Α Γυμνασίου", category: "science", difficulty: "genius", prompt: "Ποια δομή ελέγχει πολλές λειτουργίες του κυττάρου;", choices: ["Ο πυρήνας", "Η ρίζα", "Το κόκαλο", "Το νερό"], answerIndex: 0, explanation: "Ο πυρήνας περιέχει γενετικό υλικό και ελέγχει πολλές λειτουργίες του κυττάρου." },
  { id: "g1-s-2", grade: "Α Γυμνασίου", category: "science", difficulty: "genius", prompt: "Ποια είναι η μονάδα μέτρησης της δύναμης στο Διεθνές Σύστημα;", choices: ["Newton", "Μέτρο", "Λίτρο", "Βαθμός Κελσίου"], answerIndex: 0, explanation: "Η δύναμη μετριέται σε newton (Ν)." },
  { id: "g1-h-1", grade: "Α Γυμνασίου", category: "history", difficulty: "genius", prompt: "Πώς ονομαζόταν η πόλη-κράτος όπου γεννήθηκε η άμεση δημοκρατία στην αρχαιότητα;", choices: ["Αθήνα", "Ολυμπία", "Κόρινθος", "Δελφοί"], answerIndex: 0, explanation: "Στην αρχαία Αθήνα οι πολίτες συμμετείχαν άμεσα σε σημαντικές αποφάσεις." },
  { id: "g1-l-1", grade: "Α Γυμνασίου", category: "language", difficulty: "genius", prompt: "Ποια λέξη είναι επίρρημα;", choices: ["γρήγορα", "γρήγορος", "δρόμος", "τρέχω"], answerIndex: 0, explanation: "Το «γρήγορα» προσδιορίζει τον τρόπο με τον οποίο γίνεται μια ενέργεια." },
  { id: "g1-t-1", grade: "Α Γυμνασίου", category: "technology", difficulty: "genius", prompt: "Τι περιγράφει καλύτερα έναν αλγόριθμο;", choices: ["Μια σειρά σαφών βημάτων για την επίλυση ενός προβλήματος", "Ένα είδος υπολογιστή", "Ένα ηλεκτρικό καλώδιο", "Ένα παιχνίδι τύχης"], answerIndex: 0, explanation: "Ένας αλγόριθμος είναι μια οργανωμένη ακολουθία οδηγιών." },

  { id: "g2-m-1", grade: "Β Γυμνασίου", category: "math", difficulty: "genius", prompt: "Λύσε την εξίσωση: 3x = 27.", choices: ["x = 6", "x = 8", "x = 9", "x = 24"], answerIndex: 2, explanation: "Διαιρούμε και τις δύο πλευρές με 3: x = 27 ÷ 3 = 9." },
  { id: "g2-m-2", grade: "Β Γυμνασίου", category: "math", difficulty: "genius", prompt: "Δύο όμοια τρίγωνα έχουν λόγο πλευρών 2:3. Αν μια μικρή πλευρά είναι 8 εκ., η αντίστοιχη μεγάλη πλευρά είναι;", choices: ["10 εκ.", "12 εκ.", "14 εκ.", "16 εκ."], answerIndex: 1, explanation: "Από το 2 στο 3 πολλαπλασιάζουμε με 3/2. Άρα 8 × 3/2 = 12 εκ." },
  { id: "g2-m-3", grade: "Β Γυμνασίου", category: "math", difficulty: "genius", prompt: "Ποιο είναι το άθροισμα των γωνιών ενός τριγώνου;", choices: ["90°", "180°", "270°", "360°"], answerIndex: 1, explanation: "Το άθροισμα των τριών εσωτερικών γωνιών κάθε τριγώνου είναι 180°." },
  { id: "g2-s-1", grade: "Β Γυμνασίου", category: "science", difficulty: "genius", prompt: "Ποιο κύκλωμα επιτρέπει σε μία λάμπα να λειτουργεί ακόμη και αν μια άλλη καεί;", choices: ["Παράλληλο κύκλωμα", "Σειριακό κύκλωμα", "Ανοιχτό κύκλωμα", "Κύκλωμα χωρίς πηγή"], answerIndex: 0, explanation: "Σε παράλληλο κύκλωμα κάθε λάμπα έχει δικό της κλάδο." },
  { id: "g2-s-2", grade: "Β Γυμνασίου", category: "science", difficulty: "genius", prompt: "Τι εκφράζει η πυκνότητα ενός υλικού;", choices: ["Τη μάζα ανά μονάδα όγκου", "Μόνο το χρώμα", "Μόνο τη θερμοκρασία", "Τον χρόνο"], answerIndex: 0, explanation: "Η πυκνότητα συγκρίνει τη μάζα ενός υλικού με τον όγκο που καταλαμβάνει." },
  { id: "g2-h-1", grade: "Β Γυμνασίου", category: "history", difficulty: "genius", prompt: "Ποια μεγάλη αλλαγή συνδέεται με τη Βιομηχανική Επανάσταση;", choices: ["Η ευρεία χρήση μηχανών στην παραγωγή", "Η εφεύρεση της γραφής", "Η ανακάλυψη της φωτιάς", "Η κατασκευή των πυραμίδων"], answerIndex: 0, explanation: "Η Βιομηχανική Επανάσταση άλλαξε την παραγωγή με την αξιοποίηση μηχανών και εργοστασίων." },
  { id: "g2-l-1", grade: "Β Γυμνασίου", category: "language", difficulty: "genius", prompt: "Ποια πρόταση είναι απλή;", choices: ["Διάβασα το βιβλίο.", "Διάβασα το βιβλίο και έγραψα σημειώσεις.", "Όταν τελείωσα, έφυγα.", "Θα έρθω αν μπορέσω."], answerIndex: 0, explanation: "Η απλή πρόταση έχει έναν βασικό ρηματικό τύπο: «διάβασα»." },
  { id: "g2-g-1", grade: "Β Γυμνασίου", category: "geography", difficulty: "genius", prompt: "Ποια γραμμή χωρίζει τη Γη σε Βόρειο και Νότιο Ημισφαίριο;", choices: ["Ο Ισημερινός", "Ο Πρώτος Μεσημβρινός", "Ο Τροπικός του Αιγόκερω", "Ο Αρκτικός Κύκλος"], answerIndex: 0, explanation: "Ο Ισημερινός είναι ο παράλληλος που χωρίζει τη Γη σε δύο ημισφαίρια." },

  { id: "g3-m-1", grade: "Γ Γυμνασίου", category: "math", difficulty: "genius", prompt: "Για τη συνάρτηση y = 2x + 1, ποια είναι η τιμή του y όταν x = 3;", choices: ["5", "6", "7", "8"], answerIndex: 2, explanation: "Αντικαθιστούμε x = 3: y = 2 × 3 + 1 = 7." },
  { id: "g3-m-2", grade: "Γ Γυμνασίου", category: "math", difficulty: "genius", prompt: "Ένα ορθογώνιο τρίγωνο έχει κάθετες πλευρές 3 εκ. και 4 εκ. Πόση είναι η υποτείνουσα;", choices: ["5 εκ.", "6 εκ.", "7 εκ.", "8 εκ."], answerIndex: 0, explanation: "Με το Πυθαγόρειο θεώρημα: 3² + 4² = 9 + 16 = 25, άρα η υποτείνουσα είναι 5 εκ." },
  { id: "g3-m-3", grade: "Γ Γυμνασίου", category: "math", difficulty: "genius", prompt: "Σε ένα κουτί υπάρχουν 3 κόκκινες και 2 μπλε μπίλιες. Ποια είναι η πιθανότητα να πάρουμε κόκκινη μπίλια;", choices: ["2/5", "3/5", "1/2", "3/2"], answerIndex: 1, explanation: "Οι ευνοϊκές περιπτώσεις είναι 3 και οι συνολικές 5, άρα η πιθανότητα είναι 3/5." },
  { id: "g3-s-1", grade: "Γ Γυμνασίου", category: "science", difficulty: "genius", prompt: "Ποιο σωματίδιο του ατόμου έχει αρνητικό ηλεκτρικό φορτίο;", choices: ["Ηλεκτρόνιο", "Πρωτόνιο", "Νετρόνιο", "Πυρήνας"], answerIndex: 0, explanation: "Το ηλεκτρόνιο έχει αρνητικό ηλεκτρικό φορτίο." },
  { id: "g3-s-2", grade: "Γ Γυμνασίου", category: "science", difficulty: "genius", prompt: "Ποιο αέριο συνδέεται κυρίως με την ενίσχυση του φαινομένου του θερμοκηπίου από ανθρώπινες δραστηριότητες;", choices: ["Διοξείδιο του άνθρακα", "Οξυγόνο", "Ήλιο", "Υδρογόνο"], answerIndex: 0, explanation: "Οι αυξημένες συγκεντρώσεις διοξειδίου του άνθρακα ενισχύουν το φαινόμενο του θερμοκηπίου." },
  { id: "g3-h-1", grade: "Γ Γυμνασίου", category: "history", difficulty: "genius", prompt: "Γιατί οι ιστορικοί συγκρίνουν διαφορετικές πηγές;", choices: ["Για να ελέγχουν και να κατανοούν καλύτερα τις πληροφορίες", "Για να διαλέγουν την πιο μεγάλη", "Για να μη διαβάζουν", "Για να αλλάζουν το παρελθόν"], answerIndex: 0, explanation: "Η σύγκριση πηγών βοηθά να ελέγχουμε την αξιοπιστία και να βλέπουμε περισσότερες οπτικές." },
  { id: "g3-l-1", grade: "Γ Γυμνασίου", category: "language", difficulty: "genius", prompt: "Ποια πρόταση βρίσκεται σε παθητική φωνή;", choices: ["Οι μαθητές έλυσαν την άσκηση.", "Η άσκηση λύθηκε από τους μαθητές.", "Οι μαθητές λύνουν ασκήσεις.", "Θα λύσουμε την άσκηση."], answerIndex: 1, explanation: "Στην παθητική φωνή το υποκείμενο «η άσκηση» δέχεται την ενέργεια." },
  { id: "g3-t-1", grade: "Γ Γυμνασίου", category: "technology", difficulty: "genius", prompt: "Τι κάνει ένας έλεγχος δεδομένων σε ένα πρόγραμμα;", choices: ["Ελέγχει αν η είσοδος έχει αποδεκτή μορφή και τιμή", "Αλλάζει το χρώμα της οθόνης", "Σβήνει πάντα τα αρχεία", "Σταματά το διαδίκτυο"], answerIndex: 0, explanation: "Ο έλεγχος δεδομένων προστατεύει το πρόγραμμα από λανθασμένες ή απρόσμενες τιμές εισόδου." },
];
window.PAIZOMATH_GRADE_QUESTIONS = PAIZOMATH_GRADE_QUESTIONS;
window.PAIZOMATH_GRADE_POOL = function (topic) {
  var selected = window.PAIZOMATH_GRADE_FOR_AGE ? window.PAIZOMATH_GRADE_FOR_AGE() : localStorage.getItem('paizomath-selected-grade');
  return PAIZOMATH_GRADE_QUESTIONS
    .filter(function (question) { return question.grade === selected && question.category === topic; })
    .map(function (question) {
      return { id: question.id, prompt: question.prompt, choices: question.choices.slice(), correct: question.choices[question.answerIndex], explanation: question.explanation, topic: topic, grade: question.grade, difficulty: question.difficulty };
    });
};
