// Ported from Android source: lib/grade-content.ts (elementary grades).
// Each record retains the Android id, category, difficulty, prompt, choices, answerIndex, and explanation.
const PAIZOMATH_GRADE_QUESTIONS = [
  { id: "a-m-1", grade: "A Δημοτικού", category: "math", difficulty: "beginner", prompt: "Η Άννα έχει 5 μολύβια και παίρνει άλλα 3. Πόσα έχει τώρα;", choices: ["7", "8", "9", "10"], answerIndex: 1, explanation: "Προσθέτουμε 5 και 3: 5 + 3 = 8." },
  { id: "a-m-2", grade: "A Δημοτικού", category: "math", difficulty: "beginner", prompt: "Ποιος αριθμός έρχεται μετά το 19;", choices: ["18", "20", "21", "29"], answerIndex: 1, explanation: "Μετά το 19 έρχεται το 20." },
  { id: "a-l-1", grade: "A Δημοτικού", category: "language", difficulty: "beginner", prompt: "Με ποιο γράμμα αρχίζει η λέξη «μήλο»;", choices: ["Μ", "Λ", "Π", "Τ"], answerIndex: 0, explanation: "Η λέξη «μήλο» αρχίζει από το γράμμα Μ." },
  { id: "a-l-2", grade: "A Δημοτικού", category: "language", difficulty: "beginner", prompt: "Ποια λέξη είναι το όνομα ενός παιδιού;", choices: ["τρέχω", "Μαρία", "κόκκινο", "γρήγορα"], answerIndex: 1, explanation: "Η Μαρία είναι κύριο όνομα." },
  { id: "a-s-1", grade: "A Δημοτικού", category: "science", difficulty: "beginner", prompt: "Με ποιο μέρος του σώματος μυρίζουμε;", choices: ["Με τη μύτη", "Με το χέρι", "Με το πόδι", "Με το αυτί"], answerIndex: 0, explanation: "Η μύτη είναι το όργανο της όσφρησης." },
  { id: "a-k-1", grade: "A Δημοτικού", category: "knowledge", difficulty: "beginner", prompt: "Πόσοι μήνες έχει ένας χρόνος;", choices: ["7", "10", "12", "15"], answerIndex: 2, explanation: "Ένας χρόνος έχει δώδεκα μήνες." },
  { id: "a-en-1", grade: "A Δημοτικού", category: "english", difficulty: "beginner", prompt: "Τι σημαίνει η λέξη “sun”;", choices: ["Ήλιος", "Φεγγάρι", "Αστέρι", "Θάλασσα"], answerIndex: 0, explanation: "Η αγγλική λέξη “sun” σημαίνει ήλιος." },
  { id: "a-sk-1", grade: "A Δημοτικού", category: "skills", difficulty: "beginner", prompt: "Ποιο βήμα βοηθά πριν ξεκινήσεις μια εργασία;", choices: ["Να ετοιμάσω τα υλικά μου", "Να πετάξω τα βιβλία", "Να φωνάξω", "Να μην ακούσω"], answerIndex: 0, explanation: "Η προετοιμασία των υλικών βοηθά να ξεκινήσουμε οργανωμένα." },
  { id: "b-m-1", grade: "B Δημοτικού", category: "math", difficulty: "beginner", prompt: "Πόσο κάνει 23 + 14;", choices: ["35", "36", "37", "38"], answerIndex: 2, explanation: "23 + 14 = 37." },
  { id: "b-m-2", grade: "B Δημοτικού", category: "math", difficulty: "beginner", prompt: "Πόσο κάνει 50 − 20;", choices: ["20", "30", "40", "70"], answerIndex: 1, explanation: "Αν αφαιρέσουμε 2 δεκάδες από 5 δεκάδες, μένουν 3 δεκάδες: 30." },
  { id: "b-l-1", grade: "B Δημοτικού", category: "language", difficulty: "beginner", prompt: "Ποια είναι η σωστή πληθυντική μορφή του «δέντρο»;", choices: ["δέντρες", "δέντρα", "δεντρά", "δέντρι"], answerIndex: 1, explanation: "Ο πληθυντικός της λέξης «δέντρο» είναι «δέντρα»." },
  { id: "b-l-2", grade: "B Δημοτικού", category: "language", difficulty: "beginner", prompt: "Ποια λέξη είναι ρήμα;", choices: ["σχολείο", "πράσινος", "χορεύω", "τσάντα"], answerIndex: 2, explanation: "Το «χορεύω» δείχνει μια πράξη, άρα είναι ρήμα." },
  { id: "b-s-1", grade: "B Δημοτικού", category: "science", difficulty: "beginner", prompt: "Ποιο από αυτά είναι υγρό;", choices: ["Γάλα", "Πέτρα", "Μολύβι", "Αέρας"], answerIndex: 0, explanation: "Το γάλα ρέει και παίρνει το σχήμα του δοχείου, άρα είναι υγρό." },
  { id: "b-k-1", grade: "B Δημοτικού", category: "knowledge", difficulty: "beginner", prompt: "Ποια ημέρα έρχεται μετά την Κυριακή;", choices: ["Σάββατο", "Δευτέρα", "Τρίτη", "Παρασκευή"], answerIndex: 1, explanation: "Μετά την Κυριακή αρχίζει η νέα εβδομάδα με τη Δευτέρα." },
  { id: "b-p-1", grade: "B Δημοτικού", category: "physical", difficulty: "beginner", prompt: "Τι κάνουμε όταν διψάμε μετά την άσκηση;", choices: ["Πίνουμε νερό", "Δεν αναπνέουμε", "Τρέχουμε χωρίς στάση", "Φοράμε βαρύ παλτό"], answerIndex: 0, explanation: "Το νερό βοηθά το σώμα να ενυδατωθεί." },
  { id: "b-a-1", grade: "B Δημοτικού", category: "arts", difficulty: "beginner", prompt: "Ποια γραμμή είναι καμπύλη;", choices: ["Μια γραμμή σαν τόξο", "Μια ευθεία γραμμή", "Ένας αριθμός", "Ένα γράμμα"], answerIndex: 0, explanation: "Η καμπύλη γραμμή αλλάζει κατεύθυνση και μοιάζει με τόξο." },
  { id: "c-m-1", grade: "Γ Δημοτικού", category: "math", difficulty: "explorer", prompt: "Πόσο κάνει 7 × 8;", choices: ["48", "54", "56", "64"], answerIndex: 2, explanation: "Επτά φορές το οκτώ κάνει 56." },
  { id: "c-m-2", grade: "Γ Δημοτικού", category: "math", difficulty: "explorer", prompt: "Πόσο κάνει 72 ÷ 8;", choices: ["7", "8", "9", "10"], answerIndex: 2, explanation: "Επειδή 8 × 9 = 72, τότε 72 ÷ 8 = 9." },
  { id: "c-m-3", grade: "Γ Δημοτικού", category: "math", difficulty: "explorer", prompt: "Ένα μάθημα αρχίζει στις 09:00 και τελειώνει στις 10:00. Πόση ώρα διαρκεί;", choices: ["30 λεπτά", "1 ώρα", "2 ώρες", "3 ώρες"], answerIndex: 1, explanation: "Από τις 09:00 έως τις 10:00 περνά μία ώρα." },
  { id: "c-l-1", grade: "Γ Δημοτικού", category: "language", difficulty: "explorer", prompt: "Ποια πρόταση γράφεται σωστά;", choices: ["η Μαρία παίζει.", "Η Μαρία παίζει.", "Η μαρία Παίζει.", "η μαρία παίζει."], answerIndex: 1, explanation: "Η πρόταση αρχίζει με κεφαλαίο γράμμα και τελειώνει με τελεία." },
  { id: "c-g-1", grade: "Γ Δημοτικού", category: "geography", difficulty: "explorer", prompt: "Ποια κατεύθυνση δείχνει συνήθως το πάνω μέρος ενός χάρτη;", choices: ["Βορρά", "Νότο", "Ανατολή", "Δύση"], answerIndex: 0, explanation: "Στους περισσότερους χάρτες ο Βορράς βρίσκεται προς τα πάνω." },
  { id: "c-s-1", grade: "Γ Δημοτικού", category: "science", difficulty: "explorer", prompt: "Ποια αλλαγή συμβαίνει όταν το νερό ζεσταίνεται πολύ;", choices: ["Γίνεται υδρατμός", "Γίνεται πέτρα", "Γίνεται χώμα", "Γίνεται μέταλλο"], answerIndex: 0, explanation: "Με τη θέρμανση το νερό μπορεί να εξατμιστεί και να γίνει υδρατμός." },
  { id: "c-h-1", grade: "Γ Δημοτικού", category: "history", difficulty: "explorer", prompt: "Τι μπορεί να μας δείξει ένα παλιό νόμισμα;", choices: ["Στοιχεία για το παρελθόν", "Τον αυριανό καιρό", "Μόνο το βάρος του", "Μια συνταγή"], answerIndex: 0, explanation: "Τα αντικείμενα του παρελθόντος είναι πηγές που βοηθούν τους ιστορικούς." },
  { id: "c-t-1", grade: "Γ Δημοτικού", category: "technology", difficulty: "explorer", prompt: "Τι κάνουμε πριν πατήσουμε έναν άγνωστο σύνδεσμο;", choices: ["Ελέγχουμε με έναν έμπιστο ενήλικα", "Δίνουμε τον κωδικό μας", "Τον στέλνουμε παντού", "Πατάμε βιαστικά"], answerIndex: 0, explanation: "Η προσεκτική χρήση συνδέσμων βοηθά να μένουμε ασφαλείς στο διαδίκτυο." },
  { id: "d-m-1", grade: "Δ Δημοτικού", category: "math", difficulty: "explorer", prompt: "Πόσο είναι το 1/4 του 20;", choices: ["4", "5", "10", "15"], answerIndex: 1, explanation: "Χωρίζουμε το 20 σε 4 ίσα μέρη: 20 ÷ 4 = 5." },
  { id: "d-m-2", grade: "Δ Δημοτικού", category: "math", difficulty: "explorer", prompt: "Πόσο κάνει 346 + 127;", choices: ["463", "473", "483", "493"], answerIndex: 1, explanation: "346 + 127 = 473." },
  { id: "d-m-3", grade: "Δ Δημοτικού", category: "math", difficulty: "explorer", prompt: "Πόσα εκατοστά είναι 2 μέτρα;", choices: ["20", "100", "200", "2.000"], answerIndex: 2, explanation: "Κάθε μέτρο έχει 100 εκατοστά, άρα 2 μέτρα έχουν 200 εκατοστά." },
  { id: "d-l-1", grade: "Δ Δημοτικού", category: "language", difficulty: "explorer", prompt: "Ποιο είναι το επίθετο στην πρόταση «Το γρήγορο τρένο έφυγε»;", choices: ["Το", "γρήγορο", "τρένο", "έφυγε"], answerIndex: 1, explanation: "Το «γρήγορο» περιγράφει το ουσιαστικό «τρένο», άρα είναι επίθετο." },
  { id: "d-l-2", grade: "Δ Δημοτικού", category: "language", difficulty: "explorer", prompt: "Ποιο σημείο στίξης ταιριάζει στο τέλος της πρότασης «Πρόσεξε»;", choices: ["Τελεία", "Ερωτηματικό", "Θαυμαστικό", "Κόμμα"], answerIndex: 2, explanation: "Το θαυμαστικό ταιριάζει σε μια δυνατή προτροπή ή εντολή." },
  { id: "d-s-1", grade: "Δ Δημοτικού", category: "science", difficulty: "explorer", prompt: "Σε μια τροφική αλυσίδα, ποιο ζώο τρώει συνήθως τα φυτά;", choices: ["Το φυτοφάγο", "Το θηρευτικό", "Το μικρόβιο", "Το μέταλλο"], answerIndex: 0, explanation: "Τα φυτοφάγα ζώα τρέφονται με φυτά." },
  { id: "d-g-1", grade: "Δ Δημοτικού", category: "geography", difficulty: "explorer", prompt: "Τι είναι ένα νησί;", choices: ["Στεριά που περιβάλλεται από νερό", "Πολύ ψηλό βουνό", "Ένας ποταμός", "Μια έρημος"], answerIndex: 0, explanation: "Το νησί είναι κομμάτι στεριάς με νερό γύρω του." },
  { id: "d-c-1", grade: "Δ Δημοτικού", category: "civics", difficulty: "explorer", prompt: "Τι βοηθά να λυθεί μια διαφωνία στην ομάδα;", choices: ["Ήρεμη συζήτηση", "Φωνές", "Κοροϊδία", "Να μη μιλά κανείς"], answerIndex: 0, explanation: "Η ήρεμη συζήτηση βοηθά να ακουστούν όλες οι απόψεις και να βρεθεί λύση." },
  { id: "e-m-1", grade: "Ε Δημοτικού", category: "math", difficulty: "champion", prompt: "Πόσο κάνει 3,5 + 1,2;", choices: ["4,5", "4,6", "4,7", "5,7"], answerIndex: 2, explanation: "3,5 + 1,2 = 4,7." },
  { id: "e-m-2", grade: "Ε Δημοτικού", category: "math", difficulty: "champion", prompt: "Ποιο κλάσμα είναι ίσο με 2/4;", choices: ["1/2", "1/3", "2/3", "3/4"], answerIndex: 0, explanation: "Αν διαιρέσουμε αριθμητή και παρονομαστή του 2/4 με 2, παίρνουμε 1/2." },
  { id: "e-m-3", grade: "Ε Δημοτικού", category: "math", difficulty: "champion", prompt: "Ποιο είναι το εμβαδόν ορθογωνίου με μήκος 8 εκ. και πλάτος 3 εκ.;", choices: ["11 τ.εκ.", "16 τ.εκ.", "22 τ.εκ.", "24 τ.εκ."], answerIndex: 3, explanation: "Εμβαδόν = μήκος × πλάτος, άρα 8 × 3 = 24 τ.εκ." },
  { id: "e-l-1", grade: "Ε Δημοτικού", category: "language", difficulty: "champion", prompt: "Ποια λέξη είναι σύνδεσμος;", choices: ["και", "βιβλίο", "τρέχω", "γρήγορος"], answerIndex: 0, explanation: "Ο σύνδεσμος «και» ενώνει λέξεις ή προτάσεις." },
  { id: "e-h-1", grade: "Ε Δημοτικού", category: "history", difficulty: "champion", prompt: "Ποια πόλη ήταν πρωτεύουσα της Βυζαντινής Αυτοκρατορίας;", choices: ["Κωνσταντινούπολη", "Σπάρτη", "Ρώμη", "Αλεξάνδρεια"], answerIndex: 0, explanation: "Η Κωνσταντινούπολη ήταν η πρωτεύουσα της Βυζαντινής Αυτοκρατορίας." },
  { id: "e-g-1", grade: "Ε Δημοτικού", category: "geography", difficulty: "champion", prompt: "Τι δείχνει η κλίμακα ενός χάρτη;", choices: ["Τη σχέση της απόστασης στον χάρτη με την πραγματική απόσταση", "Τη θερμοκρασία", "Τις ώρες της ημέρας", "Το ύψος των ανθρώπων"], answerIndex: 0, explanation: "Η κλίμακα μάς βοηθά να υπολογίζουμε πραγματικές αποστάσεις από έναν χάρτη." },
  { id: "e-s-1", grade: "Ε Δημοτικού", category: "science", difficulty: "champion", prompt: "Ποια μορφή ενέργειας χρησιμοποιεί ένα ηλιακό πάνελ;", choices: ["Ηλιακή ενέργεια", "Μόνο ηχητική ενέργεια", "Μόνο χημική ενέργεια", "Μόνο μυϊκή ενέργεια"], answerIndex: 0, explanation: "Το ηλιακό πάνελ αξιοποιεί το φως του Ήλιου για να παράγει ηλεκτρική ενέργεια." },
  { id: "e-en-1", grade: "Ε Δημοτικού", category: "english", difficulty: "champion", prompt: "Ποια πρόταση σημαίνει «Μου αρέσει η επιστήμη»;", choices: ["I like science.", "I am science.", "Science likes I.", "Like is science."], answerIndex: 0, explanation: "Η φράση “I like science.” σημαίνει «Μου αρέσει η επιστήμη»." },
  { id: "f-m-1", grade: "ΣΤ Δημοτικού", category: "math", difficulty: "champion", prompt: "Πόσο είναι το 25% του 80;", choices: ["10", "20", "25", "40"], answerIndex: 1, explanation: "Το 25% είναι το ένα τέταρτο. Το ένα τέταρτο του 80 είναι 20." },
  { id: "f-m-2", grade: "ΣΤ Δημοτικού", category: "math", difficulty: "champion", prompt: "Πόσο κάνει 4,8 ÷ 0,6;", choices: ["0,8", "6", "8", "80"], answerIndex: 2, explanation: "4,8 ÷ 0,6 = 8, επειδή 0,6 × 8 = 4,8." },
  { id: "f-m-3", grade: "ΣΤ Δημοτικού", category: "math", difficulty: "champion", prompt: "Μια συνταγή για 4 άτομα χρειάζεται 300 γρ. αλεύρι. Πόσα χρειάζεται για 8 άτομα;", choices: ["150 γρ.", "300 γρ.", "450 γρ.", "600 γρ."], answerIndex: 3, explanation: "Τα άτομα διπλασιάζονται, οπότε διπλασιάζουμε και το αλεύρι: 300 × 2 = 600 γρ." },
  { id: "f-l-1", grade: "ΣΤ Δημοτικού", category: "language", difficulty: "champion", prompt: "Ποια πρόταση είναι σε ενεργητική φωνή;", choices: ["Το γράμμα γράφτηκε από τη Μαρία.", "Η Μαρία έγραψε το γράμμα.", "Το γράμμα θα γραφτεί.", "Το γράμμα έχει γραφτεί."], answerIndex: 1, explanation: "Στην ενεργητική φωνή το υποκείμενο, η Μαρία, κάνει την ενέργεια." },
  { id: "f-h-1", grade: "ΣΤ Δημοτικού", category: "history", difficulty: "champion", prompt: "Τι είναι ένα Σύνταγμα;", choices: ["Ο βασικός νόμος ενός κράτους", "Μια αρχαία πόλη", "Ένα μουσικό όργανο", "Ένα είδος χάρτη"], answerIndex: 0, explanation: "Το Σύνταγμα περιγράφει βασικούς κανόνες οργάνωσης ενός κράτους και τα δικαιώματα των πολιτών." },
  { id: "f-s-1", grade: "ΣΤ Δημοτικού", category: "science", difficulty: "champion", prompt: "Ποιο σύστημα του σώματος παίρνει οξυγόνο από τον αέρα;", choices: ["Αναπνευστικό", "Πεπτικό", "Μυϊκό", "Σκελετικό"], answerIndex: 0, explanation: "Το αναπνευστικό σύστημα μάς βοηθά να παίρνουμε οξυγόνο." },
  { id: "f-t-1", grade: "ΣΤ Δημοτικού", category: "technology", difficulty: "champion", prompt: "Ποιος κωδικός είναι πιο ασφαλής;", choices: ["123456", "password", "Μόνο το όνομά μου", "Μια μεγάλη φράση με γράμματα, αριθμούς και σύμβολα"], answerIndex: 3, explanation: "Οι μεγάλες, μοναδικές φράσεις με διαφορετικούς χαρακτήρες είναι δυσκολότερο να μαντευτούν." },
  { id: "f-c-1", grade: "ΣΤ Δημοτικού", category: "civics", difficulty: "champion", prompt: "Τι σημαίνει να συμμετέχουμε δημοκρατικά σε μια απόφαση τάξης;", choices: ["Ακούμε απόψεις και ψηφίζουμε με σεβασμό", "Αποφασίζει πάντα ένας", "Φωνάζουμε πιο δυνατά", "Δεν ακούμε κανέναν"], answerIndex: 0, explanation: "Η δημοκρατική συμμετοχή βασίζεται στον διάλογο, τον σεβασμό και τη δίκαιη διαδικασία." },
];
window.PAIZOMATH_GRADE_QUESTIONS = PAIZOMATH_GRADE_QUESTIONS;
window.PAIZOMATH_GRADE_POOL = function (topic) {
  var selected = localStorage.getItem('paizomath-selected-grade');
  var gradeNames = { a: 'A Δημοτικού', b: 'B Δημοτικού', c: 'Γ Δημοτικού', d: 'Δ Δημοτικού', e: 'Ε Δημοτικού', st: 'ΣΤ Δημοτικού' };
  var gradeName = gradeNames[selected];
  if (!gradeName) return [];
  return PAIZOMATH_GRADE_QUESTIONS
    .filter(function (question) { return question.grade === gradeName && question.category === topic; })
    .map(function (question) {
      return { id: question.id, prompt: question.prompt, choices: question.choices.slice(), correct: question.choices[question.answerIndex], explanation: question.explanation, topic: topic, grade: question.grade, difficulty: question.difficulty };
    });
};
